title = "MAMANのITブログ"
theme = "tranquilpeak"
baseURL = "https://blog.mamansoft.net"
googleAnalytics = "UA-36444836-1"
# はまった...
DefaultContentLanguage = "en-us"
languageCode = "ja"

publishDir = "docs"
enableEmoji = true

pygmentsUseClasses = true
pygmentsCodefences = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  post = ":year/:month/:day/:slug/"

[author]
  name = "Tadashi Aikawa"
  bio = "Productivity creator"
  picture = "https://avatars1.githubusercontent.com/u/9500018?s=460&v=4"

[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "search"
  name = "Search"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-search\"></i>"
  url = "/search"
[[menu.main]]
  weight = 3
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 4
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-tags\"></i>"
  url = "/tags"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\"></i>"
  url = "https://github.com/tadashi-aikawa"
[[menu.links]]
  weight = 2
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/Tadashi_MAMAN"
[[menu.links]]
  weight = 3
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
  description = "Webエンジニアによる エンジニアリング/業務効率化/ガジェット に関するブログ"
  coverImage = "https://dl.dropboxusercontent.com/s/l96rzrxzd4ztsgy/cover.jpg"
  favicon = "https://avatars1.githubusercontent.com/u/9500018?s=460&v=4"

  sidebarBehavior = 2
  thumbnailImage = true
  thumbnailImagePosition = "left"
  autoThumbnailImage = true
  imageGallery = true
  hierarchicalCategories = true

  [params.header.rightLink]
    url = "/search"
    icon = "search"

  [[params.customJS]]
    src = "//cdn.embedly.com/widgets/platform.js"
    async = true

  [[params.customJS]]
    src = "https://use.fontawesome.com/releases/v5.6.1/js/all.js"
    async = true

  [[params.customJS]]
    src = "https://use.fontawesome.com/releases/v5.6.1/js/v4-shims.js"
    async = true

  [[params.customCSS]]
    href = "css/mystyle.css"

  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook-official"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [[params.sharingOptions]]
    name = "Google+"
    icon = "fa-google-plus"
    url = "https://plus.google.com/share?url=%s"
